import type { Marketplace, ProductDetail } from "./types";

function img(seed: string, i = 1) {
  return `https://picsum.photos/seed/s2b-${seed}-${i}/800/800`;
}

function make(
  id: string,
  seed: string,
  title: string,
  titleBn: string,
  category: string,
  priceMin: number,
  priceMax: number,
  moq: number,
  shopName: string,
  city: string,
  ordersHint: string,
  attributes: { label: string; value: string }[],
  description: string,
): ProductDetail {
  return {
    id,
    marketplace: "1688",
    title,
    titleBn,
    category,
    priceMin,
    priceMax,
    currency: "CNY",
    moq,
    imageUrl: img(seed, 1),
    images: [img(seed, 1), img(seed, 2), img(seed, 3), img(seed, 4)],
    shopName,
    city,
    ordersHint,
    productUrl: `https://detail.1688.com/offer/${id}.html`,
    priceTiers: [
      { minQty: moq, price: priceMax },
      { minQty: moq * 5, price: Number(((priceMin + priceMax) / 2).toFixed(2)) },
      { minQty: moq * 20, price: priceMin },
    ],
    attributes,
    description,
  };
}

const base1688: ProductDetail[] = [
  make(
    "681204551903",
    "usb-c-cable",
    "60W USB-C to USB-C fast charging cable, braided nylon, 1m / 2m",
    "৬০ওয়াট ইউএসবি-সি ফাস্ট চার্জিং ক্যাবল",
    "electronics accessories",
    3.2,
    5.8,
    50,
    "Shenzhen Yuxin Digital Factory",
    "Shenzhen",
    "12k+ ordered",
    [
      { label: "Material", value: "Braided nylon + aluminium shell" },
      { label: "Lengths", value: "1m / 1.5m / 2m" },
      { label: "Output", value: "60W PD, 3A" },
      { label: "Packing", value: "200 pcs / carton, 6.5 kg" },
    ],
    "High-turnover accessory line for BD mobile shops. Mixed length and colour cartons are accepted above 500 pcs.",
  ),
  make(
    "624318870021",
    "bubble-mailer",
    "Poly bubble mailer courier bags, custom print, 10 sizes",
    "বাবল মেইলার কুরিয়ার ব্যাগ",
    "packaging",
    0.28,
    0.75,
    500,
    "Yiwu Hengsheng Packing Co.",
    "Yiwu",
    "48k+ ordered",
    [
      { label: "Sizes", value: "A000 to A9" },
      { label: "Print", value: "1-2 colour logo from 3000 pcs" },
      { label: "Sealing", value: "Self-adhesive strip" },
      { label: "Packing", value: "500 pcs / bale" },
    ],
    "Everyday e-commerce packaging. Cheap per unit but bulky, sea freight is almost always the right mode here.",
  ),
  make(
    "593280114427",
    "zipper-trims",
    "Nylon zipper rolls #5 with sliders, garment trims, 40 colours",
    "নাইলন জিপার রোল #৫ · গার্মেন্টস ট্রিমস",
    "garment trims",
    1.1,
    2.4,
    200,
    "Guangzhou Jinlun Zipper",
    "Guangzhou",
    "9.4k+ ordered",
    [
      { label: "Gauge", value: "#3 / #5 / #8" },
      { label: "Tape", value: "Polyester, dyed to Pantone on request" },
      { label: "Sliders", value: "Auto-lock, nickel or gunmetal" },
      { label: "MOQ note", value: "200 m per colour" },
    ],
    "Standard trim supply for Dhaka and Narayanganj garment units. Colour matching needs a physical swatch.",
  ),
  make(
    "712994330158",
    "cordless-drill",
    "21V cordless drill driver set with 2 batteries and case",
    "২১ভি কর্ডলেস ড্রিল ড্রাইভার সেট",
    "home tools",
    42,
    78,
    10,
    "Jinhua Powertool Manufacturing",
    "Yiwu",
    "3.2k+ ordered",
    [
      { label: "Battery", value: "2 × 2.0Ah Li-ion" },
      { label: "Torque", value: "25 + 1 settings" },
      { label: "Case", value: "Blow-moulded, 46 pc bit set" },
      { label: "Carton", value: "6 sets / carton, 21 kg" },
    ],
    "Battery goods need declaration before booking. We confirm the shipping lane before you pay the supplier.",
  ),
  make(
    "660112884930",
    "facial-roller",
    "Stainless ice roller & gua sha beauty tool set, gift box",
    "আইস রোলার ও গুয়াশা বিউটি টুল সেট",
    "beauty tools",
    6.5,
    13.9,
    30,
    "Shenzhen Meiya Beauty Tools",
    "Shenzhen",
    "7.8k+ ordered",
    [
      { label: "Material", value: "304 stainless + ABS handle" },
      { label: "Box", value: "Retail gift box included" },
      { label: "Custom logo", value: "From 500 sets" },
      { label: "Carton", value: "100 sets / carton" },
    ],
    "Strong online-retail item in BD. Light and compact, so air freight stays affordable.",
  ),
  make(
    "588417002265",
    "phone-lcd",
    "Replacement LCD assembly for popular Android models, tested",
    "অ্যান্ড্রয়েড ফোনের রিপ্লেসমেন্ট এলসিডি",
    "phone parts",
    38,
    145,
    5,
    "Guangzhou Huaqiang Parts Trade",
    "Guangzhou",
    "22k+ ordered",
    [
      { label: "Grade", value: "INCELL / OLED options" },
      { label: "Testing", value: "100% powered on before packing" },
      { label: "Packing", value: "Foam brick, 10 pcs per box" },
      { label: "Warranty", value: "Supplier DOA replacement policy" },
    ],
    "Fragile and high value, hand carry is the usual pick for repair shops that cannot risk crush damage.",
  ),
  make(
    "705523118644",
    "backpack",
    "Water-resistant laptop backpack, 15.6 inch, USB port",
    "ওয়াটার রেজিস্ট্যান্ট ল্যাপটপ ব্যাকপ্যাক",
    "bags",
    28,
    54,
    20,
    "Baoding Chenyu Bags Factory",
    "Guangzhou",
    "15k+ ordered",
    [
      { label: "Fabric", value: "900D polyester, PU coated" },
      { label: "Capacity", value: "28 L" },
      { label: "Logo", value: "Embroidery or rubber patch from 300 pcs" },
      { label: "Carton", value: "20 pcs / carton, high CBM" },
    ],
    "High volume per kg. Sea freight to Chattogram keeps the landed cost sane on anything above 200 pieces.",
  ),
  make(
    "639870044512",
    "led-panel",
    "Slim LED ceiling panel light 18W/24W, 3-colour switch",
    "স্লিম এলইডি সিলিং প্যানেল লাইট",
    "lights",
    7.9,
    18.5,
    50,
    "Zhongshan Guzhen Lighting",
    "Guangzhou",
    "31k+ ordered",
    [
      { label: "Power", value: "12W / 18W / 24W / 36W" },
      { label: "Driver", value: "Isolated, 220V" },
      { label: "CRI", value: ">80" },
      { label: "Carton", value: "40 pcs / carton" },
    ],
    "Popular with BD electrical wholesalers. Ask us about driver voltage suitability before ordering large lots.",
  ),
  make(
    "674401238890",
    "airfryer",
    "5.5L digital air fryer, non-stick basket, OEM available",
    "৫.৫ লিটার ডিজিটাল এয়ার ফ্রায়ার",
    "kitchen",
    118,
    182,
    10,
    "Foshan Kanglai Home Appliance",
    "Guangzhou",
    "5.6k+ ordered",
    [
      { label: "Capacity", value: "3.5L / 5.5L / 8L" },
      { label: "Plug", value: "UK / EU options" },
      { label: "Certificate", value: "CE, supplier documents on request" },
      { label: "Carton", value: "2 pcs / carton, 8.4 kg" },
    ],
    "Appliances are bulky and dutiable. We give an honest landed estimate before you commit the supplier deposit.",
  ),
  make(
    "618230997741",
    "building-blocks",
    "Generic building block sets, 300-1200 pcs, ASTM-style plastic",
    "বিল্ডিং ব্লক সেট (জেনেরিক)",
    "toys",
    9.5,
    36,
    24,
    "Shantou Chenghai Toy Works",
    "Shenzhen",
    "4.1k+ ordered",
    [
      { label: "Material", value: "ABS, non-branded generic design" },
      { label: "Age", value: "6+" },
      { label: "Packing", value: "Colour box, 24 sets / carton" },
      { label: "Note", value: "No licensed character copies" },
    ],
    "We only move generic, non-infringing toy designs. Licensed character copies are refused at booking.",
  ),
  make(
    "690315520037",
    "power-strip",
    "Multi-socket power strip with USB, 2500W, surge protection",
    "ইউএসবি সহ মাল্টি সকেট পাওয়ার স্ট্রিপ",
    "electronics accessories",
    11.5,
    26,
    30,
    "Ningbo Ruixin Electric",
    "Yiwu",
    "18k+ ordered",
    [
      { label: "Sockets", value: "3 / 4 / 6 way + 2 USB" },
      { label: "Cable", value: "1.8m pure copper" },
      { label: "Standard", value: "UK / universal socket options" },
      { label: "Carton", value: "40 pcs / carton" },
    ],
    "Confirm UK-standard pins for the Bangladesh market, universal sockets sell slower in retail.",
  ),
  make(
    "651789003324",
    "kraft-box",
    "Custom printed kraft mailer boxes, corrugated, brand print",
    "কাস্টম প্রিন্টেড ক্রাফট মেইলার বক্স",
    "packaging",
    0.9,
    3.4,
    300,
    "Dongguan Xinyi Printing",
    "Guangzhou",
    "6.9k+ ordered",
    [
      { label: "Board", value: "E-flute / 3-ply corrugated" },
      { label: "Print", value: "CMYK offset, matt lamination" },
      { label: "Proof", value: "Digital dieline before production" },
      { label: "Lead time", value: "8-12 days production" },
    ],
    "Add production lead time on top of shipping time. Plan roughly 6 weeks total if you go by sea.",
  ),
  make(
    "608844217750",
    "sewing-thread",
    "Polyester sewing thread cones 40/2, 5000 yards, 200 shades",
    "পলিয়েস্টার সেলাই সুতা কোন ৪০/২",
    "garment trims",
    2.6,
    4.2,
    100,
    "Ningbo Sanhe Thread Co.",
    "Yiwu",
    "11k+ ordered",
    [
      { label: "Count", value: "40/2, 30/2, 20/3" },
      { label: "Yardage", value: "5000 yd per cone" },
      { label: "Shades", value: "200 stock colours" },
      { label: "Carton", value: "120 cones / carton" },
    ],
    "Stock shades ship in days; custom dye lots need 2 extra weeks at the mill.",
  ),
  make(
    "667092330415",
    "hair-dryer",
    "Negative ion hair dryer 1800W, foldable handle, salon grade",
    "নেগেটিভ আয়ন হেয়ার ড্রায়ার ১৮০০ওয়াট",
    "beauty tools",
    32,
    69,
    20,
    "Shenzhen Aiwei Appliance",
    "Shenzhen",
    "8.3k+ ordered",
    [
      { label: "Power", value: "1600W / 1800W / 2200W" },
      { label: "Voltage", value: "220V" },
      { label: "Accessories", value: "2 nozzles + diffuser" },
      { label: "Carton", value: "20 pcs / carton" },
    ],
    "Motor appliances: check voltage and plug type before ordering. We flag anything that will fail in BD sockets.",
  ),
  make(
    "633158802290",
    "hand-tools",
    "46-piece household hand tool kit in blow case",
    "৪৬ পিস হাউজহোল্ড হ্যান্ড টুল কিট",
    "home tools",
    24,
    46,
    12,
    "Hangzhou Great Star Trade",
    "Yiwu",
    "2.9k+ ordered",
    [
      { label: "Contents", value: "Pliers, drivers, wrench, tape, bits" },
      { label: "Finish", value: "Chrome vanadium, polished" },
      { label: "Case", value: "PP blow case with handle" },
      { label: "Carton", value: "12 kits / carton, 26 kg" },
    ],
    "Heavy metal goods, sea freight is nearly always cheaper unless you need it for a specific tender date.",
  ),
  make(
    "645220119983",
    "solar-light",
    "Solar street light 100W-300W, IP65, remote + motion sensor",
    "সোলার স্ট্রিট লাইট · আইপি৬৫",
    "lights",
    96,
    340,
    2,
    "Yangzhou Hengyi Solar",
    "Guangzhou",
    "1.8k+ ordered",
    [
      { label: "Panel", value: "Monocrystalline, integrated" },
      { label: "Battery", value: "LiFePO4" },
      { label: "Pole", value: "Optional, sold separately" },
      { label: "Carton", value: "1 pc / carton" },
    ],
    "Lithium battery goods have shipping restrictions. Talk to us before paying, the lane matters here.",
  ),
  make(
    "679413550028",
    "steel-cookware",
    "Stainless steel cookware set, tri-ply base, 8 pieces",
    "স্টেইনলেস স্টিল কুকওয়্যার সেট",
    "kitchen",
    138,
    260,
    6,
    "Chaozhou Hongfa Kitchenware",
    "Guangzhou",
    "2.2k+ ordered",
    [
      { label: "Grade", value: "304 stainless, tri-ply base" },
      { label: "Pieces", value: "8 / 12 / 16 piece sets" },
      { label: "Handles", value: "Bakelite or steel" },
      { label: "Carton", value: "2 sets / carton, 19 kg" },
    ],
    "Dense and heavy. Sea to Chattogram is the only sensible mode above a few sets.",
  ),
  make(
    "615507739911",
    "tote-bag",
    "Canvas tote bags, 12oz cotton, screen print available",
    "ক্যানভাস টোট ব্যাগ · স্ক্রিন প্রিন্ট",
    "bags",
    5.4,
    12.8,
    100,
    "Quanzhou Hongyu Bag Factory",
    "Guangzhou",
    "13k+ ordered",
    [
      { label: "Fabric", value: "10oz / 12oz cotton canvas" },
      { label: "Print", value: "Screen or DTF, up to 4 colours" },
      { label: "Size", value: "38 × 42 cm standard" },
      { label: "Carton", value: "200 pcs / bale" },
    ],
    "Popular corporate gift item. Send your artwork as vector so the factory can proof it quickly.",
  ),
];


function retarget(p: ProductDetail, marketplace: Marketplace): ProductDetail {
  if (marketplace === "alibaba") {
    return {
      ...p,
      marketplace,
      currency: "USD",
      priceMin: p.priceMin ? Number((p.priceMin / 6.9).toFixed(2)) : undefined,
      priceMax: p.priceMax ? Number((p.priceMax / 6.9).toFixed(2)) : undefined,
      priceTiers: p.priceTiers?.map((t) => ({
        minQty: t.minQty,
        price: Number((t.price / 6.9).toFixed(2)),
      })),
      productUrl: `https://www.alibaba.com/product-detail/${p.id}.html`,
    };
  }
  return { ...p, marketplace };
}

function amazon(
  asin: string,
  seed: string,
  title: string,
  titleBn: string,
  category: string,
  priceMin: number,
  priceMax: number,
  shopName: string,
  attributes: { label: string; value: string }[],
  description: string,
): ProductDetail {
  return {
    id: asin,
    marketplace: "amazon",
    title,
    titleBn,
    category,
    priceMin,
    priceMax,
    currency: "USD",
    moq: 1,
    imageUrl: img(seed, 1),
    images: [img(seed, 1), img(seed, 2), img(seed, 3)],
    shopName,
    city: "US warehouse",
    ordersHint: "Amazon listing",
    productUrl: `https://www.amazon.com/dp/${asin}`,
    attributes,
    description,
  };
}

const amazonProducts: ProductDetail[] = [
  amazon(
    "B0C7KND8LM",
    "amz-monitor-arm",
    "Single monitor desk mount arm, gas spring, up to 32 inch",
    "মনিটর ডেস্ক মাউন্ট আর্ম",
    "office equipment",
    38.99,
    58.0,
    "HuAnuo Store",
    [
      { label: "Fits", value: "17 to 32 inch, up to 19.8 lbs" },
      { label: "Mount", value: "Clamp or grommet" },
      { label: "Ship weight", value: "3.1 kg boxed" },
    ],
    "Common Amazon buy for Dhaka office fitouts. We buy on your behalf, receive at our US forwarder, then air freight to Dhaka.",
  ),
  amazon(
    "B08N5WRWNW",
    "amz-baby-monitor",
    "Video baby monitor with 5 inch screen and night vision",
    "ভিডিও বেবি মনিটর",
    "baby products",
    89.99,
    119.0,
    "Nannio Official",
    [
      { label: "Range", value: "300m open field" },
      { label: "Battery", value: "12 hour standby" },
      { label: "Ship weight", value: "1.2 kg boxed" },
    ],
    "Brand item not reliably available on local shelves. Personal import quantities only, duty applies on landing.",
  ),
  amazon(
    "B09XJ6FZ4T",
    "amz-espresso",
    "Semi automatic espresso machine, 20 bar, stainless body",
    "এসপ্রেসো মেশিন · ২০ বার",
    "kitchen appliances",
    169.0,
    239.0,
    "Casabrews",
    [
      { label: "Voltage", value: "110V, needs a converter in BD" },
      { label: "Ship weight", value: "9.4 kg boxed" },
      { label: "Mode", value: "Air freight or sea consolidation" },
    ],
    "Heavy and voltage sensitive. Ask us about a 220V equivalent from 1688 before you commit to the US listing.",
  ),
];

export const mockProducts: ProductDetail[] = [
  ...base1688.map((p, i) => retarget(p, i % 5 === 3 ? "alibaba" : "1688")),
  ...amazonProducts,
];
