/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as MoreRouteImport } from './routes/more'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProhibitedRouteImport } from './routes/prohibited'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SourcingRouteImport } from './routes/sourcing'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as ApiProductsByImageRouteImport } from './routes/api/products/by-image'
import { Route as ApiProductsByUrlRouteImport } from './routes/api/products/by-url'
import { Route as ApiProductsDetailRouteImport } from './routes/api/products/detail'
import { Route as ApiProductsSearchRouteImport } from './routes/api/products/search'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicImgRouteImport } from './routes/api/public/img'
import { Route as ProductMarketplaceIdRouteImport } from './routes/product.$marketplace.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProhibitedRoute = ProhibitedRouteImport.update({
  id: '/prohibited',
  path: '/prohibited',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcingRoute = SourcingRouteImport.update({
  id: '/sourcing',
  path: '/sourcing',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsByImageRoute = ApiProductsByImageRouteImport.update({
  id: '/api/products/by-image',
  path: '/api/products/by-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsByUrlRoute = ApiProductsByUrlRouteImport.update({
  id: '/api/products/by-url',
  path: '/api/products/by-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsDetailRoute = ApiProductsDetailRouteImport.update({
  id: '/api/products/detail',
  path: '/api/products/detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsSearchRoute = ApiProductsSearchRouteImport.update({
  id: '/api/products/search',
  path: '/api/products/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgRoute = ApiPublicImgRouteImport.update({
  id: '/api/public/img',
  path: '/api/public/img',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductMarketplaceIdRoute = ProductMarketplaceIdRouteImport.update({
  id: '/product/$marketplace/$id',
  path: '/product/$marketplace/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/more': typeof MoreRoute
  '/privacy': typeof PrivacyRoute
  '/prohibited': typeof ProhibitedRoute
  '/quote': typeof QuoteRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sourcing': typeof SourcingRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/api/products/by-image': typeof ApiProductsByImageRoute
  '/api/products/by-url': typeof ApiProductsByUrlRoute
  '/api/products/detail': typeof ApiProductsDetailRoute
  '/api/products/search': typeof ApiProductsSearchRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/product/$marketplace/$id': typeof ProductMarketplaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/more': typeof MoreRoute
  '/privacy': typeof PrivacyRoute
  '/prohibited': typeof ProhibitedRoute
  '/quote': typeof QuoteRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sourcing': typeof SourcingRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides': typeof GuidesIndexRoute
  '/api/products/by-image': typeof ApiProductsByImageRoute
  '/api/products/by-url': typeof ApiProductsByUrlRoute
  '/api/products/detail': typeof ApiProductsDetailRoute
  '/api/products/search': typeof ApiProductsSearchRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/product/$marketplace/$id': typeof ProductMarketplaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/more': typeof MoreRoute
  '/privacy': typeof PrivacyRoute
  '/prohibited': typeof ProhibitedRoute
  '/quote': typeof QuoteRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sourcing': typeof SourcingRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/api/products/by-image': typeof ApiProductsByImageRoute
  '/api/products/by-url': typeof ApiProductsByUrlRoute
  '/api/products/detail': typeof ApiProductsDetailRoute
  '/api/products/search': typeof ApiProductsSearchRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/product/$marketplace/$id': typeof ProductMarketplaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/catalog'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/more'
    | '/privacy'
    | '/prohibited'
    | '/quote'
    | '/refunds'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/sourcing'
    | '/terms'
    | '/track'
    | '/account'
    | '/admin'
    | '/guides/$slug'
    | '/guides/'
    | '/api/products/by-image'
    | '/api/products/by-url'
    | '/api/products/detail'
    | '/api/products/search'
    | '/api/public/health'
    | '/api/public/img'
    | '/product/$marketplace/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/catalog'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/more'
    | '/privacy'
    | '/prohibited'
    | '/quote'
    | '/refunds'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/sourcing'
    | '/terms'
    | '/track'
    | '/account'
    | '/admin'
    | '/guides/$slug'
    | '/guides'
    | '/api/products/by-image'
    | '/api/products/by-url'
    | '/api/products/detail'
    | '/api/products/search'
    | '/api/public/health'
    | '/api/public/img'
    | '/product/$marketplace/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/catalog'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/more'
    | '/privacy'
    | '/prohibited'
    | '/quote'
    | '/refunds'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/sourcing'
    | '/terms'
    | '/track'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/guides/$slug'
    | '/guides/'
    | '/api/products/by-image'
    | '/api/products/by-url'
    | '/api/products/detail'
    | '/api/products/search'
    | '/api/public/health'
    | '/api/public/img'
    | '/product/$marketplace/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MoreRoute: typeof MoreRoute
  PrivacyRoute: typeof PrivacyRoute
  ProhibitedRoute: typeof ProhibitedRoute
  QuoteRoute: typeof QuoteRoute
  RefundsRoute: typeof RefundsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SourcingRoute: typeof SourcingRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ApiProductsByImageRoute: typeof ApiProductsByImageRoute
  ApiProductsByUrlRoute: typeof ApiProductsByUrlRoute
  ApiProductsDetailRoute: typeof ApiProductsDetailRoute
  ApiProductsSearchRoute: typeof ApiProductsSearchRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicImgRoute: typeof ApiPublicImgRoute
  ProductMarketplaceIdRoute: typeof ProductMarketplaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prohibited': {
      id: '/prohibited'
      path: '/prohibited'
      fullPath: '/prohibited'
      preLoaderRoute: typeof ProhibitedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing': {
      id: '/sourcing'
      path: '/sourcing'
      fullPath: '/sourcing'
      preLoaderRoute: typeof SourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/by-image': {
      id: '/api/products/by-image'
      path: '/api/products/by-image'
      fullPath: '/api/products/by-image'
      preLoaderRoute: typeof ApiProductsByImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/by-url': {
      id: '/api/products/by-url'
      path: '/api/products/by-url'
      fullPath: '/api/products/by-url'
      preLoaderRoute: typeof ApiProductsByUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/detail': {
      id: '/api/products/detail'
      path: '/api/products/detail'
      fullPath: '/api/products/detail'
      preLoaderRoute: typeof ApiProductsDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/search': {
      id: '/api/products/search'
      path: '/api/products/search'
      fullPath: '/api/products/search'
      preLoaderRoute: typeof ApiProductsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img': {
      id: '/api/public/img'
      path: '/api/public/img'
      fullPath: '/api/public/img'
      preLoaderRoute: typeof ApiPublicImgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$marketplace/$id': {
      id: '/product/$marketplace/$id'
      path: '/product/$marketplace/$id'
      fullPath: '/product/$marketplace/$id'
      preLoaderRoute: typeof ProductMarketplaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  MoreRoute: MoreRoute,
  PrivacyRoute: PrivacyRoute,
  ProhibitedRoute: ProhibitedRoute,
  QuoteRoute: QuoteRoute,
  RefundsRoute: RefundsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SourcingRoute: SourcingRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ApiProductsByImageRoute: ApiProductsByImageRoute,
  ApiProductsByUrlRoute: ApiProductsByUrlRoute,
  ApiProductsDetailRoute: ApiProductsDetailRoute,
  ApiProductsSearchRoute: ApiProductsSearchRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicImgRoute: ApiPublicImgRoute,
  ProductMarketplaceIdRoute: ProductMarketplaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
